services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - ${A}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/
    networks:
      - api-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    # restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 8090:8090
    networks:
      - api-net
    depends_on:
      - db

networks:
  api-net:

volumes:
  postgres_data:
